name: test
developers: 
  - 
    name: dev1
    email: zpzhaoa@eazybuilder.com
  - 
    name: dev2
    email: zpzhaoa@eazybuilder.com
scm: 
  type: svn
  url: http://localhost
  user: zhaozhoupeng
  password: 1111
  
deployInfo: 
  host: 127.0.0.1
  user: root
  password: root
   
registry: 
  schema: http
  url: ${registry_IP}:5000
  user: 
  password: 