apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 10
  labels:
    app: ci-jenkins-client
  name: ci-jenkins-client
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ci-jenkins-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ci-jenkins-client
    spec:
      containers:
      - image: registry.eazybuilder-devops.cn/${NAMESPACE}/jenkins-client
        imagePullPolicy: Always
        name: ci-jenkins-client
        ports:
        - containerPort: 8080
          name: 8080tcp02
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
      imagePullSecrets:
      - name: harbor